name: VStarStack

on:
  release:
    types: [published]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build sdist
        run: |
          rm -f ./dist/*
          python -m build . --sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
