name: VStarStack

on:
  release:
    types: [published]

jobs:

  publish:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          python -m pip install pytest
          python -m pip install pytest-cov
          python -m pip install build
          python -m pip install cython
          python -m pip install wheel
          python -m pip install --upgrade setuptools
          python -m pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint --rcfile=pylintrc --fail-under=9 src/vstarstack
      - name: Build & Install
        run: |
          python -m build . --wheel -n
          find ./dist/*.whl | xargs python -m pip install
      - name: Test that tools launches
        run: |
          vstarstack
      - name: Build sdist
        run: |
          rm -f ./dist/*
          python -m build . --sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
